services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER:-root}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD:-rootroot}"
    command: [
      "server",
      "/data",
      "--console-address",
      ":9001"
    ]
    volumes:
      - minio-data:/data

  object-storage-maintenance:
    build:
      context: ./
      dockerfile: Dockerfile
    image: object-storage-maintenance
    container_name: object-storage-maintenance
    environment:
      AWS_ACCESS_KEY: "${AWS_ACCESS_KEY}"
      AWS_SECRET_KEY: "${AWS_SECRET_KEY}"
      AWS_REGION: "${AWS_REGION:-us-east-1}"
      OBJECT_STORAGE_ENDPOINT: "${OBJECT_STORAGE_ENDPOINT:-http://minio:9000}"
      OBJECT_STORAGE_BUCKET: "${OBJECT_STORAGE_BUCKET:-test}"
    command: [
      "archive",
      "--src-bucket", "${OBJECT_STORAGE_BUCKET:-test}",
      "--src-prefix", "${SRC_PREFIX:-audit/}",
      "--dst-bucket", "${OBJECT_STORAGE_BUCKET:-test}",
      "--dst-prefix", "${DST_PREFIX:-.archive/}",
    ]
    depends_on:
      - minio

networks:
  guest:

volumes:
  minio-data: